### ISSUE TITLE
Problems with my docker config

### ISSUE THREAD

**Issue by EBS-DarkD** [ledgersmb/LedgerSMB#8416]
Version: 1.11.17
Browser: chrome and firefox
What happened?

I am running this in a portainer docker stack which already has an active postgres 16 container running

```yaml
  lsmb:
    image: ledgersmb/ledgersmb:latest
    container_name: lsmb
    networks:
      t2_proxy:
        ipv4_address: 192.168.101.41 
    ports:
      - "5762:5762"
    environment:
      POSTGRES_HOST: 192.168.101.230
      POSTGRES_PORT: 5432
      LSMB_WORKERS: ${LSMB_WORKERS:-5}
    volumes:
      - ./ledgersmb/conf:/srv/ledgersmb/local/conf:rw
```

When I go into the setup.pl and add the database credentials for the account I've setup in the postfix container to create a new database, I get the following error

```plain
Error!

Could not connect to database: could not translate host name "localhost" to address: Temporary failure in name resolution at lib/LedgerSMB/Scripts/setup.pm line 1123.

dbversion: 1.11.17, company:
```

Note: For the POSTGRES_HOST I've tried the IP address, and the container name with no difference. The database server is up and has several other containers using it

I am also facing an issue with the permissions on the volume /srv/ledgersmb/local/conf
The logs show

```plain
/usr/local/bin/start.sh: line 71: ./local/conf/ledgersmb.yaml: Permission denied
/usr/local/bin/start.sh: line 113: ./local/conf/ledgersmb.000.yaml: Permission denied
--------- LEDGERSMB CONFIGURATION:  ledgersmb.conf
cat: ./local/conf/ledgersmb.yaml: No such file or directory
--------- LEDGERSMB CONFIGURATION --- END
```

when I open a console and check the permissions and ownership of the files and folders in /srv/ledgersmb
ownership of all files and folders is 1000:1000 except local which is www-data:root

How can I change the ownership of the mounted volume?

I'm a bit stumped with this setup and hope that someone can help!
